// <auto-generated />
using System;
using CryptocurrencyQuotesLibrary.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CryptocurrencyQuotesMigrations.Migrations.CryptocurrencyDb
{
    [DbContext(typeof(CryptocurrencyDbContext))]
    [Migration("20210712091952_AddedCryptocurrency_CryptocurrencyDbContext")]
    partial class AddedCryptocurrency_CryptocurrencyDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CryptocurrencyQuotesLibrary.Models.DbModels.Cryptocurrency", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MarketCap")
                        .HasColumnType("decimal(30,15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PercentChange1h")
                        .HasColumnType("decimal(30,15)");

                    b.Property<decimal>("PercentChange24h")
                        .HasColumnType("decimal(30,15)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(30,15)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cryptocurrency");
                });
#pragma warning restore 612, 618
        }
    }
}
